### ISSUE TITLE
Importing From Mod Browser Issue

### ISSUE THREAD

**Issue by Duvent-mindustry** [pixaxeofpixie/AzureFlareTech#1]
when importing from the mod browser
![Screenshot (1336)](https://user-images.githubusercontent.com/73276338/115139136-e0948100-a062-11eb-96b6-8d8b9e9dbf97.png)

**Comment by pixaxeofpixie** [comment]
lol cuz i dont make a release(mod browser imports java mods from releases)
maybe today

**Comment by Duvent-mindustry** [comment]
Alright
